from django.conf.urls import url
from by_products import views

urlpatterns = [
    url(r'^serve/by/product/stock/record/$', views.serve_by_product_stock_record),
    url(r'^create/input/stock/record/$', views.create_input_stock_record),
    url(r'^serve/new/grn/number/$', views.serve_new_grn_number),
    url(r'^update/grn/back/to/original/digit/$', views.update_grn_back_to_original_digit),
    url(r'^serve/goods/record/for/selected/product/$', views.serve_goods_record_for_selected_product),
    url(r'^serve/by/product/list/$', views.serve_by_product_list),
    url(r'^register/or/update/by/product/$', views.register_or_update_by_product),
    url(r'^save/or/update/business/type/wise/discount/price/for/by/product/$', views.save_or_update_business_type_wise_discount_price_for_by_product),
    url(r'^serve/business/type/wise/discount/price/dict/for/by/product/$', views.serve_business_type_wise_discount_price_dict_for_by_product),
    url(r'^serve/business/type/list/for/by/product/price/$', views.serve_business_type_list_for_by_product_price),
    url(r'^remove/business/type/wise/product/for/by/product/$', views.remove_business_type_wise_product_for_by_product),
    url(r'^serve/by/product/list/for/order/$', views.serve_by_product_list_for_order),
    url(r'^serve/by/product/availablity/and/price/list/$', views.serve_by_product_availablity_and_price_list),
    url(r'^serve/wallet/balance/and/order/category/$', views.serve_wallet_balance_and_order_category),
    url(r'^register/order/for/by/product/agent/$', views.register_order_for_by_product_agent),
    url(r'^register/order/for/by/product/employee/$', views.register_order_for_by_product_employee),
    url(r'^create/encrypeted/string/and/make/request/for/by/product/$', views.create_encrypeted_string_and_make_request_for_by_product),
    url(r'^serve/by/product/order/history/for/selected/date/range/$', views.serve_by_product_order_history_for_selected_date_range),
    url(r'^serve/transaction/log/data/for/by/product/order/$', views.serve_transaction_log_data_for_by_product_order),
    url(r'^serve/order/category/for/order/$', views.serve_order_category_for_order),
    url(r'^serve/by/product/order/list/for/gatepass/$', views.serve_by_product_order_list_for_gatepass),
    url(r'^prepare/gate/pass/for/by/product/$', views.prepare_gate_pass_for_by_product),
    url(r'^prepare/gate/pass/for/by/product/employee/$', views.prepare_gate_pass_for_by_product_employee),
    url(r'^serve/by/product/order/list/for/selected/business/$', views.serve_by_product_order_list_for_selected_business),
    url(r'^serve/by/product/order/list/for/employee/$', views.serve_by_product_order_list_for_employee),
    url(r'^serve/counter/orders/for/by/product/$', views.serve_counter_orders_for_by_product),
    url(r'^serve/business/details/for/by/product/order/$', views.serve_business_details_for_by_product_order),
    url(r'^serve/counter/wise/sale/summary/for/byproducts/$', views.serve_counter_wise_sale_summary_for_byproducts),
    url(r'^download/gate/pass/for/by/product/$', views.download_gate_pass_for_by_product),
    url(r'^download/gate/pass/for/by/product/employee/$', views.download_gate_pass_for_by_product_employee),
    url(r'^serve/counter/sale/by/products/report/$', views.serve_counter_sale_by_products_report),
    url(r'^serve/by/product/counters/$', views.serve_by_product_counters),
    url(r'^serve/billing/preview/for/employee/order/$', views.serve_billing_preview_for_employee_order),
    url(r'^return/grn/and/order/to/main/employee/order/$', views.return_grn_and_order_to_main_employee_order),
    url(r'^serve/goods/product/record/for/employee/order/$', views.serve_goods_product_record_for_employee_order),
    url(r'^serve/purchase/company/$', views.serve_purchase_company),
    url(r'^register/purchase/company/$', views.register_purchase_company),
    url(r'^serve/sale/group/payment/method/$', views.serve_sale_group_payment_method),
    url(r'^serve/daily/sale/quantity/business/wise/$', views.serve_daily_sale_quantity_business_wise),
    url(r'^serve/daily/sale/quantity/product/wise/$', views.serve_daily_sale_quantity_product_wise),
    url(r'^update/daily/sale/quantity/business/wise/$', views.update_daily_sale_quantity_business_wise),
    url(r'^update/edit/daily/sale/quantity/business/wise/$', views.update_edit_daily_sale_quantity_business_wise),
    url(r'^serve/monthly/sale/regisred/dealers/$', views.monthly_sale_regisred_dealers),
    url(r'^serve/monthly/sale/non/regisred/dealers/$', views.monthly_sale_non_regisred_dealers),
    url(r'^serve/monthly/sale/regisred/unregisred/dealers/$', views.monthly_sale_register_and_unregisred_dealers),
    url(r'^serve/monthly/product/sales/abstract/report/$', views.monthly_product_sales_abstract_report),
    url(r'^download/cash/receipt/$', views.download_cash_receipt),
    url(r'^serve/vehicle/gate/pass/and/order/$', views.serve_vehicle_gate_pass_and_order),
    url(r'^prepare/vehicle/gate/pass/$', views.prepare_vehicle_gate_pass),
    url(r'^serve/daily/stock/report/in/excel/$', views.serve_daily_stock_report_in_excel),
    url(r'^serve/daily/stock/report/in/pdf/$', views.serve_daily_stock_report_in_pdf),
    url(r'^serve/daily/close/status/$', views.serve_daily_close_status),
    url(r'^close/daily/sale/$', views.close_daily_sale),
    url(r'^open/daily/sale/$', views.open_daily_sale),
    url(r'^serve/daily/sale/for/selected/date/$', views.serve_daily_sale_for_selected_date),
    url(r'^serve/daily/cash/and/credit/statement/$', views.serve_daily_cash_and_credit_statement),
    url(r'^serve/daily/cash/and/credit/statement/excel/$', views.serve_daily_cash_and_credit_statement_excel),
    url(r'^daily/sale/upload/$', views.daily_sale_upload),
    url(r'^delete/overall/sale/and/grn/$', views.delete_overall_sale_and_grn),
    url(r'^serve/sales/tax/abstract/report/$', views.serve_sales_tax_abstract_report),
    url(r'^delete/selected/by/product/order/$', views.delete_selected_by_product_order),
    url(r'^serve_json_for_govt_upload/$', views.serve_json_for_govt_upload),
    url(r'^serve_govt_gst_bill/$', views.serve_govt_gst_bill),
    url(r'^serve/byproduct/analytic/report/$',views.serve_byproduct_analytic_report),

]
