# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-03-12 09:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ByProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('short_name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=9)),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=9)),
                ('is_refrigerated', models.BooleanField(default=False)),
                ('gst_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('minimum_quantity', models.PositiveIntegerField(default=1)),
                ('display_ordinal', models.PositiveIntegerField()),
                ('color', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ByProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ByProductUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=10)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ByProudctCurrentAvailablity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_now', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity_now_time', models.DateTimeField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('by_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.ByProduct')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_goods_receipt_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_goods_receipt_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceiptMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grn_number', models.CharField(max_length=15)),
                ('grn_date', models.DateTimeField()),
                ('bill_number', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('po_number', models.CharField(max_length=50)),
                ('po_date', models.DateTimeField()),
                ('dc_number', models.CharField(max_length=50)),
                ('dc_date', models.DateTimeField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_master_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_master_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceiptMasterCodeBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_digit', models.CharField(max_length=15)),
                ('code_prefix', models.CharField(blank=True, max_length=15, null=True)),
                ('code_suffix', models.CharField(blank=True, max_length=15, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceiptRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_at_receipt', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity_now', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity_now_time', models.DateTimeField()),
                ('expiry_date', models.DateTimeField()),
                ('goods_receipt_code', models.CharField(max_length=15)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('by_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.ByProduct')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_created_by', to=settings.AUTH_USER_MODEL)),
                ('goods_receipt_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.GoodsReceiptMaster')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipt_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceiptRecordCodeBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_digit', models.CharField(max_length=15)),
                ('code_prefix', models.CharField(blank=True, max_length=15, null=True)),
                ('code_suffix', models.CharField(blank=True, max_length=15, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='byproduct',
            name='by_product_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.ByProductGroup'),
        ),
        migrations.AddField(
            model_name='byproduct',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.ByProductUnit'),
        ),
        migrations.AlterUniqueTogether(
            name='byproduct',
            unique_together=set([('by_product_group', 'name', 'quantity', 'unit')]),
        ),
    ]
