# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-03-16 12:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0120_auto_20210113_0727'),
        ('by_products', '0002_goodsreceiptmastercodebank_temp_last_digit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTypeWiseByProductDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BusinessType')),
                ('by_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.ByProduct')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_type_wise_by_product_discount_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_type_wise_by_product_discount_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessTypeWiseByProductDiscountTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business_type_wise_discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.BusinessTypeWiseByProductDiscount')),
                ('product_discount_ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_type_wise_by_product_discount_end_date_created_by', to=settings.AUTH_USER_MODEL)),
                ('product_discount_started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_type_wise_by_product_discount_start_date_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessWiseByProductDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Business')),
                ('by_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.ByProduct')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_wise_by_product_discount_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_wise_by_product_discount_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessWiseByProductDiscountTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business_wise_discount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.BusinessWiseByProductDiscount')),
                ('product_discount_ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_type_by_product_discount_end_date_created_by', to=settings.AUTH_USER_MODEL)),
                ('product_discount_started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_type_by_product_discount_start_date_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ByProductBusinessTypeConcessionMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BusinessType')),
                ('by_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.ByProduct')),
                ('concession_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ConcessionType')),
            ],
        ),
    ]
