# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-03-18 09:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_auto_20210113_0727'),
        ('by_products', '0003_businesstypewisebyproductdiscount_businesstypewisebyproductdiscounttrace_businesswisebyproductdiscou'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTypeOrderCategoryeMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BusinessType')),
            ],
        ),
        migrations.CreateModel(
            name='OrderCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='businesstypeordercategoryemap',
            name='order_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.OrderCategory'),
        ),
        migrations.AddField(
            model_name='businesstypeordercategoryemap',
            name='payment_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.PaymentOption'),
        ),
    ]
