# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-03-20 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_auto_20210113_0727'),
        ('by_products', '0004_auto_20210318_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByProductAgentWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('agent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.Agent')),
            ],
        ),
    ]
