# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-03-22 01:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_auto_20210113_0727'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('by_products', '0005_byproductagentwallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='BySale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('by_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.ByProduct')),
            ],
        ),
        migrations.CreateModel(
            name='BySaleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=15, unique=True)),
                ('ordered_date', models.DateField(db_index=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Business')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_product_sale_group_modified_by', to=settings.AUTH_USER_MODEL)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_product_sale_group_created_by', to=settings.AUTH_USER_MODEL)),
                ('ordered_via', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.OrderedVia')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PaymentStatus')),
            ],
        ),
        migrations.CreateModel(
            name='BySaleGroupOrderCodeBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_digit', models.CharField(max_length=15)),
                ('code_prefix', models.CharField(blank=True, max_length=15, null=True)),
                ('code_suffix', models.CharField(blank=True, max_length=15, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BySaleGroupPaymentRequestMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_done', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('by_sale_group', models.ManyToManyField(to='by_products.BySaleGroup')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PaymentRequest')),
            ],
        ),
        migrations.CreateModel(
            name='SaleStatusForByProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TempBySale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('by_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.ByProduct')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_product_temp_sale_modified_by', to=settings.AUTH_USER_MODEL)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_product_temp_sale_ordered_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TempBySaleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=15, unique=True)),
                ('ordered_date', models.DateField(db_index=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Business')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_product_temp_sale_group_modified_by', to=settings.AUTH_USER_MODEL)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_product_temp_sale_group_created_by', to=settings.AUTH_USER_MODEL)),
                ('ordered_via', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.OrderedVia')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PaymentStatus')),
                ('sale_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.SaleStatusForByProduct')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='TempBySaleGroupOrderCodeBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_digit', models.CharField(max_length=15)),
                ('code_prefix', models.CharField(blank=True, max_length=15, null=True)),
                ('code_suffix', models.CharField(blank=True, max_length=15, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='tempbysale',
            name='temp_by_sale_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.TempBySaleGroup'),
        ),
        migrations.AddField(
            model_name='bysalegrouppaymentrequestmap',
            name='temp_sale_group',
            field=models.ManyToManyField(to='by_products.TempBySaleGroup'),
        ),
        migrations.AddField(
            model_name='bysalegroup',
            name='sale_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.SaleStatusForByProduct'),
        ),
        migrations.AddField(
            model_name='bysalegroup',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Zone'),
        ),
        migrations.AddField(
            model_name='bysale',
            name='by_sale_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.BySaleGroup'),
        ),
        migrations.AddField(
            model_name='bysale',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_product_sale_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bysale',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_product_sale_ordered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tempbysalegroup',
            unique_together=set([('business', 'order_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='tempbysale',
            unique_together=set([('temp_by_sale_group', 'by_product')]),
        ),
        migrations.AlterUniqueTogether(
            name='bysalegroup',
            unique_together=set([('business', 'order_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='bysale',
            unique_together=set([('by_sale_group', 'by_product')]),
        ),
    ]
