# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-03-22 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_auto_20210113_0727'),
        ('by_products', '0006_auto_20210322_0101'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounterEmployeeTraceBySaleGroupMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('by_sale_group', models.ManyToManyField(to='by_products.BySaleGroup')),
                ('counter_employee_trace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.CounterEmployeeTraceMap')),
            ],
        ),
    ]
