# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-03-22 04:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0120_auto_20210113_0727'),
        ('by_products', '0007_counteremployeetracebysalegroupmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='ByProductTransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_approved_time', models.DateTimeField()),
                ('wallet_balance_before_this_transaction', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wallet_balance_after_transaction_approval', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('cheque_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.TransactionChequeDetails')),
                ('data_entered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_product_transaction_initiated_user', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_product_transaction_log_modified_by', to=settings.AUTH_USER_MODEL)),
                ('transacted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_product_agent_user_id', to=settings.AUTH_USER_MODEL)),
                ('transacted_via', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TransactedVia')),
                ('transaction_approval_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TransactionApprovalStatus')),
                ('transaction_approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_product_transaction_approved_by', to=settings.AUTH_USER_MODEL)),
                ('transaction_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TransactionDirection')),
                ('transaction_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TransactionMode')),
                ('transaction_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.TransactionStatus')),
            ],
        ),
    ]
