# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-03-23 04:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_auto_20210113_0727'),
        ('by_products', '0008_byproducttransactionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='BySaleGroupTransactionTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transacted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wallet_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wallet_return_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_wallet_used', models.BooleanField(default=False)),
                ('order_sale_group_json', models.TextField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('bank_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='by_product_bank_transaction_log', to='by_products.ByProductTransactionLog')),
                ('by_sale_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.BySaleGroup')),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Counter')),
                ('counter_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='by_product_counter_transaction_log', to='by_products.ByProductTransactionLog')),
                ('sale_group_order_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SaleGroupOrderType')),
                ('wallet_return_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='by_product_wallet_return_transaction_log', to='by_products.ByProductTransactionLog')),
                ('wallet_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='by_product_wallet_transaction_log', to='by_products.ByProductTransactionLog')),
            ],
        ),
    ]
