# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-03-24 11:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('by_products', '0009_bysalegrouptransactiontrace'),
    ]

    operations = [
        migrations.CreateModel(
            name='BySaleGroupGatepassMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepated_at', models.DateTimeField()),
                ('gate_pass_file', models.FileField(blank=True, max_length=1000, null=True, upload_to=main.models.get_agent_aadhar_image)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('by_sale_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.BySaleGroup')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceiptRecordBySaleMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dispatched', models.DecimalField(decimal_places=2, max_digits=9)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('by_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.BySale')),
                ('goods_receipt_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.GoodsReceiptRecord')),
            ],
        ),
    ]
