# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-03-24 11:36
from __future__ import unicode_literals

import by_products.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('by_products', '0010_bysalegroupgatepassmap_goodsreceiptrecordbysalemap'),
    ]

    operations = [
        migrations.CreateModel(
            name='BySaleGroupGatepass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prepated_at', models.DateTimeField()),
                ('gate_pass_file', models.FileField(blank=True, max_length=1000, null=True, upload_to=by_products.models.get_agent_by_product_gatepass)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('by_sale_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.BySaleGroup')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='bysalegroupgatepassmap',
            name='by_sale_group',
        ),
        migrations.RemoveField(
            model_name='bysalegroupgatepassmap',
            name='prepared_by',
        ),
        migrations.DeleteModel(
            name='BySaleGroupGatepassMap',
        ),
    ]
