# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-03-26 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0012_auto_20210326_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptrecord',
            name='cgst_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='goodsreceiptrecord',
            name='igst_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='goodsreceiptrecord',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='goodsreceiptrecord',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='goodsreceiptrecord',
            name='sgst_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='goodsreceiptrecord',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
