# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-03-26 10:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0013_auto_20210326_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptmaster',
            name='bill_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='goodsreceiptmaster',
            name='dc_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceiptmaster',
            name='dc_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
