# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-03-27 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0014_auto_20210326_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bysalegroupgatepass',
            name='by_sale_group',
        ),
        migrations.RemoveField(
            model_name='bysalegroupgatepass',
            name='prepared_by',
        ),
        migrations.DeleteModel(
            name='BySaleGroupGatepass',
        ),
    ]
