# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-03-27 07:47
from __future__ import unicode_literals

import by_products.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('by_products', '0015_auto_20210327_0745'),
    ]

    operations = [
        migrations.CreateModel(
            name='BySaleGroupGatepass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_number', models.CharField(max_length=15)),
                ('dc_date', models.DateTimeField()),
                ('bill_number', models.CharField(max_length=15)),
                ('bill_date', models.DateTimeField()),
                ('gate_pass_file_now', models.FileField(blank=True, max_length=1000, null=True, upload_to=by_products.models.get_agent_by_product_gatepass_now)),
                ('gate_pass_file_for_history', models.FileField(blank=True, max_length=1000, null=True, upload_to=by_products.models.get_agent_by_product_gatepass_for_future)),
                ('prepated_at', models.DateTimeField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('by_sale_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.BySaleGroup')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
