# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-03-27 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0016_bysalegroupgatepass'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatepassBillCodeBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_digit', models.CharField(max_length=15)),
                ('code_prefix', models.CharField(blank=True, max_length=15, null=True)),
                ('code_suffix', models.CharField(blank=True, max_length=15, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GatepassDCCodeBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_digit', models.CharField(max_length=15)),
                ('code_prefix', models.CharField(blank=True, max_length=15, null=True)),
                ('code_suffix', models.CharField(blank=True, max_length=15, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
