# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-03-27 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0017_gatepassbillcodebank_gatepassdccodebank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ByProudctCurrentAvailablity',
            new_name='ByProductCurrentAvailablity',
        ),
        migrations.AddField(
            model_name='bysalegroup',
            name='cgst_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bysalegroup',
            name='sgst_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempbysalegroup',
            name='cgst_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempbysalegroup',
            name='sgst_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
