# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-03-27 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0018_auto_20210327_1109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bysalegroup',
            name='cgst_value',
        ),
        migrations.RemoveField(
            model_name='bysalegroup',
            name='sgst_value',
        ),
        migrations.RemoveField(
            model_name='tempbysalegroup',
            name='cgst_value',
        ),
        migrations.RemoveField(
            model_name='tempbysalegroup',
            name='sgst_value',
        ),
        migrations.AddField(
            model_name='bysale',
            name='cgst_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bysale',
            name='sgst_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bysale',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempbysale',
            name='cgst_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempbysale',
            name='sgst_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tempbysale',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
