# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-03-31 09:10
from __future__ import unicode_literals

import by_products.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_auto_20210113_0727'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('by_products', '0021_auto_20210329_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeOrderBySale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sgst_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('by_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.ByProduct')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeOrderBySaleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_code', models.CharField(max_length=15, unique=True)),
                ('ordered_date', models.DateField(db_index=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Business')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_product_employee_order_sale_group_modified_by', to=settings.AUTH_USER_MODEL)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_product_employee_order_sale_group_created_by', to=settings.AUTH_USER_MODEL)),
                ('ordered_via', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.OrderedVia')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PaymentStatus')),
                ('sale_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.SaleStatusForByProduct')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Zone')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeOrderBySaleGroupGatepass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_number', models.CharField(max_length=15)),
                ('dc_date', models.DateTimeField()),
                ('bill_number', models.CharField(max_length=15)),
                ('bill_date', models.DateTimeField()),
                ('dc_file', models.FileField(blank=True, max_length=1000, null=True, upload_to=by_products.models.get_agent_by_product_gatepass_dc)),
                ('bill_file', models.FileField(blank=True, max_length=1000, null=True, upload_to=by_products.models.get_agent_by_product_gatepass_bill)),
                ('prepated_at', models.DateTimeField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('employeee_order_by_sale_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.EmployeeOrderBySaleGroup')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeReturnBySale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cgst_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sgst_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('by_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.ByProduct')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeReturnBySaleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateField(db_index=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Business')),
                ('employeee_order_by_sale_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.EmployeeOrderBySaleGroup')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_product_employee_return_sale_group_modified_by', to=settings.AUTH_USER_MODEL)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_product_employee_return_sale_group_created_by', to=settings.AUTH_USER_MODEL)),
                ('ordered_via', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.OrderedVia')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PaymentStatus')),
                ('sale_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.SaleStatusForByProduct')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Zone')),
            ],
        ),
        migrations.AddField(
            model_name='employeereturnbysale',
            name='employeee_return_by_sale_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.EmployeeReturnBySaleGroup'),
        ),
        migrations.AddField(
            model_name='employeereturnbysale',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_product_employee_return_sale_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeereturnbysale',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_product_employee_return_sale_ordered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeorderbysale',
            name='employeee_order_by_sale_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.EmployeeOrderBySaleGroup'),
        ),
        migrations.AddField(
            model_name='employeeorderbysale',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_product_employee_order_sale_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeeorderbysale',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_product_employee_order_sale_ordered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='employeereturnbysalegroup',
            unique_together=set([('business', 'employeee_order_by_sale_group')]),
        ),
        migrations.AlterUniqueTogether(
            name='employeereturnbysale',
            unique_together=set([('employeee_return_by_sale_group', 'by_product')]),
        ),
        migrations.AlterUniqueTogether(
            name='employeeorderbysalegroup',
            unique_together=set([('business', 'order_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='employeeorderbysale',
            unique_together=set([('employeee_order_by_sale_group', 'by_product')]),
        ),
    ]
