# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-04-27 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0023_auto_20210401_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptrecord',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='goodsreceiptrecord',
            name='price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='goodsreceiptrecord',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
