# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-10-01 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0024_auto_20210427_0659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesstypewisebyproductdiscounttrace',
            old_name='discounted_price',
            new_name='base_price',
        ),
        migrations.RemoveField(
            model_name='businesstypewisebyproductdiscount',
            name='discounted_price',
        ),
        migrations.AddField(
            model_name='businesstypewisebyproductdiscount',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesstypewisebyproductdiscount',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='businesstypewisebyproductdiscount',
            name='igst_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='businesstypewisebyproductdiscount',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesstypewisebyproductdiscount',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='businesstypewisebyproductdiscounttrace',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='businesstypewisebyproductdiscounttrace',
            name='igst_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='businesstypewisebyproductdiscounttrace',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='byproduct',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='byproduct',
            name='hsn_code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='byproduct',
            name='igst_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='byproduct',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='businesstypewisebyproductdiscounttrace',
            name='mrp',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='byproduct',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='byproduct',
            name='mrp',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
