# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-10-13 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0026_auto_20211001_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='bysalegroup',
            name='round_off_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bysalegroup',
            name='value_before_round_off',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
