# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-01-10 06:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('by_products', '0027_auto_20211013_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=100)),
                ('pan_number', models.CharField(max_length=100)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='goodsreceiptmaster',
            name='po_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='goodsreceiptmaster',
            name='po_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
