# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-01-10 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0028_auto_20220110_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasecompany',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='purchasecompany',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='purchasecompany',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
