# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-01-10 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0029_auto_20220110_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goodsreceiptmaster',
            name='source',
        ),
        migrations.AddField(
            model_name='goodsreceiptmaster',
            name='purchase_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='by_products.PurchaseCompany'),
        ),
    ]
