# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-01-10 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0031_auto_20220110_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstypewisebyproductdiscount',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='businesstypewisebyproductdiscount',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='businesstypewisebyproductdiscounttrace',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='businesstypewisebyproductdiscounttrace',
            name='mrp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
