# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-01-10 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0033_auto_20220110_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='bysalegrouppaymentmethod',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
