# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-01-24 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0035_businesswisedailysaleupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesswisedailysaleupdate',
            name='is_yesterday_sale_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businesswisedailysaleupdate',
            name='closing_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
