# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-02-10 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0141_agentprofile_gst_number'),
        ('by_products', '0038_bysalegroupcashreceipt'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashReceiptAccountBusinesstypeMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BusinessType')),
            ],
        ),
        migrations.CreateModel(
            name='CashReceiptAccountMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=100)),
                ('account_code', models.CharField(max_length=15)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashReceiptCodeBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_digit', models.CharField(max_length=15)),
                ('code_prefix', models.CharField(blank=True, max_length=15, null=True)),
                ('code_suffix', models.CharField(blank=True, max_length=15, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='cashreceiptaccountbusinesstypemap',
            name='cash_receipt_account_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='by_products.CashReceiptAccountMaster'),
        ),
    ]
