# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-02-12 05:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0040_auto_20220212_0514'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashReceiptAccountBusinesstypeMap',
            new_name='CashReceiptAccountPaymentMethodMap',
        ),
    ]
