# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-02-16 05:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0044_auto_20220216_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclegatepass',
            name='order_from',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehiclegatepass',
            name='order_to',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
