# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-02-16 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0045_auto_20220216_0544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclegatepass',
            old_name='prepated_at',
            new_name='prepared_at',
        ),
    ]
