# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-02-18 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0046_auto_20220216_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptrecord',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
