# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-02-21 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0047_auto_20220218_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsreceiptrecord',
            name='cgst_value',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='goodsreceiptrecord',
            name='igst_value',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='goodsreceiptrecord',
            name='sgst_value',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=10),
        ),
    ]
