# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-02-28 05:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0050_dailygoodsreceiptrecordbysalemap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysaleclosetrace',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailysaleclosetrace',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sale_closed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
