# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-04-01 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0051_auto_20220228_0559'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bysalegroup',
            name='is_vehicle_gatepass_taken',
        ),
        migrations.RemoveField(
            model_name='vehiclegatepass',
            name='by_sale_group',
        ),
        migrations.AddField(
            model_name='bysalegroupgatepass',
            name='is_vehicle_gatepass_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclegatepass',
            name='by_sale_group_gate_pass',
            field=models.ManyToManyField(to='by_products.BySaleGroupGatepass'),
        ),
    ]
