# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-05-09 02:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0144_auto_20220417_1008'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('by_products', '0052_auto_20220401_0038'),
    ]

    operations = [
        migrations.CreateModel(
            name='BySaleGroupDeleteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordered_date_time', models.DateTimeField()),
                ('delete_date_time', models.DateTimeField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Business')),
                ('deleted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_sale_group_order_deleted_by', to=settings.AUTH_USER_MODEL)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='by_sale_group_order_placed_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
