# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-07-26 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('by_products', '0053_bysalegroupdeletelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstypewisebyproductdiscount',
            name='base_price',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='businesstypewisebyproductdiscount',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='businesstypewisebyproductdiscount',
            name='igst_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='businesstypewisebyproductdiscount',
            name='mrp',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='businesstypewisebyproductdiscount',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='businesstypewisebyproductdiscounttrace',
            name='base_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='businesstypewisebyproductdiscounttrace',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='businesstypewisebyproductdiscounttrace',
            name='igst_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='businesstypewisebyproductdiscounttrace',
            name='mrp',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='businesstypewisebyproductdiscounttrace',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='byproduct',
            name='base_price',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='byproduct',
            name='cgst_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='byproduct',
            name='igst_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='byproduct',
            name='mrp',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='byproduct',
            name='sgst_amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='bysale',
            name='cgst_value',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bysale',
            name='cost',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bysale',
            name='sgst_value',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bysale',
            name='total_cost',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bysalegroup',
            name='round_off_value',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bysalegroup',
            name='value_before_round_off',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='goodsreceiptrecordbysalemap',
            name='cgst_value',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='goodsreceiptrecordbysalemap',
            name='cost',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='goodsreceiptrecordbysalemap',
            name='sgst_value',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='goodsreceiptrecordbysalemap',
            name='total_cost',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
    ]
