# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-13 02:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0058_businesstype_display_ordinal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySessionllyBusinessllySaleInPacketsCansBuckets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('route', models.CharField(max_length=250)),
                ('sold_to', models.CharField(max_length=50)),
                ('tm500_pkt', models.PositiveSmallIntegerField(default=0)),
                ('std250_pkt', models.PositiveSmallIntegerField(default=0)),
                ('std500_pkt', models.PositiveSmallIntegerField(default=0)),
                ('fcm500_pkt', models.PositiveSmallIntegerField(default=0)),
                ('tmcan', models.PositiveSmallIntegerField(default=0)),
                ('smcan', models.PositiveSmallIntegerField(default=0)),
                ('fcmcan', models.PositiveSmallIntegerField(default=0)),
                ('curd500_pkt', models.PositiveSmallIntegerField(default=0)),
                ('curd150_pkt', models.PositiveSmallIntegerField(default=0)),
                ('cupcurd_box', models.PositiveSmallIntegerField(default=0)),
                ('curdbucket', models.PositiveSmallIntegerField(default=0)),
                ('lassi200', models.PositiveSmallIntegerField(default=0)),
                ('buttermilk200', models.PositiveSmallIntegerField(default=0)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Business')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Session')),
            ],
        ),
    ]
