# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-13 02:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysessionllybusinessllysaleinpacketscansbuckets',
            name='modified_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailysessionllybusinessllysaleinpacketscansbuckets',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsbs_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
