# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-13 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20200513_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysessionllybusinessllysaleinpacketscansbuckets',
            old_name='buttermilk200',
            new_name='buttermilk200_pkt',
        ),
        migrations.RenameField(
            model_name='dailysessionllybusinessllysaleinpacketscansbuckets',
            old_name='lassi200',
            new_name='lassi200_pkt',
        ),
    ]
