# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-13 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20200513_0258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysessionllybusinessllysaleinpacketscansbuckets',
            old_name='curdbucket',
            new_name='curd_bucket',
        ),
    ]
