# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-13 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20200513_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysessionllybusinessllysaleinpacketscansbuckets',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Route'),
        ),
    ]
