# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-13 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_auto_20200513_0534'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysessionllybusinessllysale',
            name='cupcurd_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
