# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-13 09:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0009_dailysessionllyroutellysale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailysessionllybusinessllysale',
            old_name='fcm500_price',
            new_name='fcm500_unit_price',
        ),
        migrations.RenameField(
            model_name='dailysessionllybusinessllysale',
            old_name='std250_price',
            new_name='std250_unit_price',
        ),
        migrations.RenameField(
            model_name='dailysessionllybusinessllysale',
            old_name='std500_price',
            new_name='std500_unit_price',
        ),
        migrations.RenameField(
            model_name='dailysessionllybusinessllysale',
            old_name='tmcan_price',
            new_name='tmcan_unit_price',
        ),
        migrations.RenameField(
            model_name='dailysessionllyroutellysale',
            old_name='fcm500_price',
            new_name='fcm500_unit_price',
        ),
        migrations.RenameField(
            model_name='dailysessionllyroutellysale',
            old_name='std250_price',
            new_name='std250_unit_price',
        ),
        migrations.RenameField(
            model_name='dailysessionllyroutellysale',
            old_name='std500_price',
            new_name='std500_unit_price',
        ),
        migrations.RenameField(
            model_name='dailysessionllyroutellysale',
            old_name='tmcan_price',
            new_name='tmcan_unit_price',
        ),
    ]
