# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-13 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_businesstype_display_ordinal'),
        ('report', '0011_dailysessionllyzonallysale'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysessionllybusinessllysale',
            name='business_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.BusinessType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysessionllybusinessllysale',
            name='union',
            field=models.CharField(default='Coimbatore', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dailysessionllybusinessllysale',
            name='zone',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='main.Zone'),
            preserve_default=False,
        ),
    ]
