# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-14 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0013_auto_20200513_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysessionllyzonallysale',
            name='union',
            field=models.CharField(default='COIMBATORE Union', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dailysessionllybusinessllysale',
            name='delivery_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dailysessionllybusinessllysale',
            name='sold_to',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dailysessionllybusinessllysale',
            name='union',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
