# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-14 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0015_auto_20200514_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysessionllyzonallysale',
            name='delivery_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='dailysessionllyzonallysale',
            name='sold_to',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='dailysessionllyzonallysale',
            name='union',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
