# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-15 03:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_businesstype_display_ordinal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0017_auto_20200514_0624'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySessionllyBusinessTypellySale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField(db_index=True)),
                ('union', models.CharField(db_index=True, max_length=50)),
                ('sold_to', models.CharField(db_index=True, max_length=50)),
                ('tm500_pkt', models.PositiveIntegerField(default=0)),
                ('tm500_litre', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('tm500_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tm500_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('std250_pkt', models.PositiveIntegerField(default=0)),
                ('std250_litre', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('std250_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('std250_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('std500_pkt', models.PositiveIntegerField(default=0)),
                ('std500_litre', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('std500_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('std500_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fcm500_pkt', models.PositiveIntegerField(default=0)),
                ('fcm500_litre', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('fcm500_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fcm500_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tmcan', models.PositiveIntegerField(default=0)),
                ('tmcan_litre', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('tmcan_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tmcan_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('smcan', models.PositiveIntegerField(default=0)),
                ('smcan_litre', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('smcan_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('smcan_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fcmcan', models.PositiveIntegerField(default=0)),
                ('fcmcan_litre', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('fcmcan_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fcmcan_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('curd500_pkt', models.PositiveIntegerField(default=0)),
                ('curd500_kgs', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('curd500_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('curd500_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('curd150_pkt', models.PositiveIntegerField(default=0)),
                ('curd150_kgs', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('curd150_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('curd150_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cupcurd_box', models.PositiveIntegerField(default=0)),
                ('cupcurd_count', models.PositiveSmallIntegerField(default=0)),
                ('cupcurd_kgs', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('cupcurd_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cupcurd_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('curd_bucket', models.PositiveIntegerField(default=0)),
                ('curd_bucket_kgs', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('curd_bucket_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('curd_bucket_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lassi200_pkt', models.PositiveIntegerField(default=0)),
                ('lassi200_kgs', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('lassi200_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('lassi200_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('buttermilk200_pkt', models.PositiveIntegerField(default=0)),
                ('buttermilk200_litre', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('buttermilk200_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('buttermilk200_unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BusinessType')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsbts_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Session')),
            ],
        ),
    ]
