# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-18 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0018_dailysessionllybusinesstypellysale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysessionllybusinessllysale',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Business'),
        ),
        migrations.AlterField(
            model_name='dailysessionllybusinessllysale',
            name='business_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.BusinessType'),
        ),
    ]
