# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-22 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0020_dailysessionllyunionllysale'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysessionllybusinessllysale',
            name='fcm1000_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysessionllybusinessllysale',
            name='fcm1000_litre',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysessionllybusinessllysale',
            name='fcm1000_pkt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailysessionllybusinessllysale',
            name='fcm1000_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysessionllybusinesstypellysale',
            name='fcm1000_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysessionllybusinesstypellysale',
            name='fcm1000_litre',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysessionllybusinesstypellysale',
            name='fcm1000_pkt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailysessionllybusinesstypellysale',
            name='fcm1000_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysessionllyroutellysale',
            name='fcm1000_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysessionllyroutellysale',
            name='fcm1000_litre',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysessionllyroutellysale',
            name='fcm1000_pkt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailysessionllyroutellysale',
            name='fcm1000_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysessionllyunionllysale',
            name='fcm1000_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysessionllyunionllysale',
            name='fcm1000_litre',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysessionllyunionllysale',
            name='fcm1000_pkt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailysessionllyunionllysale',
            name='fcm1000_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysessionllyzonallysale',
            name='fcm1000_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysessionllyzonallysale',
            name='fcm1000_litre',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysessionllyzonallysale',
            name='fcm1000_pkt',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailysessionllyzonallysale',
            name='fcm1000_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
