# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-12-30 06:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0024_dailyscriptrunlog_dailyscriptrunproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyscriptrunlog',
            name='date_of_delivery',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
