# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-04-16 05:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0121_auto_20210331_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_code', models.CharField(max_length=50)),
                ('cmpny_code', models.CharField(max_length=50)),
                ('trnsctn_nmbr', models.CharField(max_length=50)),
                ('tranaction_id', models.CharField(max_length=20)),
                ('transaction_pkey', models.CharField(max_length=50)),
                ('salegroup_id', models.CharField(max_length=50)),
                ('booth_code', models.CharField(max_length=10)),
                ('customer_code', models.CharField(max_length=50)),
                ('product_list', models.TextField()),
                ('user_code', models.CharField(max_length=50)),
                ('device_type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('rid', models.CharField(max_length=50)),
                ('crn', models.CharField(max_length=50)),
                ('comission_amnt', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('commission_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('gst_amount', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('cheque_number', models.CharField(max_length=50)),
                ('cheque_date', models.DateField()),
                ('bank_name', models.CharField(max_length=50)),
                ('branch_name', models.CharField(max_length=50)),
                ('transaction_mode', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=50)),
                ('clrnce_date', models.DateField()),
                ('crtd_date', models.DateField()),
                ('athrsd_date', models.DateField()),
                ('aggregrator', models.CharField(max_length=50)),
                ('bank_date', models.DateField()),
                ('is_rid_matched', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BankTransactionMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField()),
                ('uploaded_count', models.PositiveIntegerField()),
                ('mismatch_count', models.PositiveIntegerField()),
                ('excel_file', models.FileField(upload_to=None)),
                ('file_name', models.CharField(blank=True, max_length=100, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankTransactionPaymentResponseMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.BankTransaction')),
                ('bank_transaction_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.BankTransactionMaster')),
                ('payment_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PaymentRequestResponse')),
            ],
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='bank_transaction_master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.BankTransactionMaster'),
        ),
    ]
