# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-04-16 06:02
from __future__ import unicode_literals

from django.db import migrations, models
import transaction.models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransactionmaster',
            name='excel_file',
            field=models.FileField(upload_to=transaction.models.get_uploaded_excel_from_bank),
        ),
    ]
