# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-04-16 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_auto_20210416_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='athrsd_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='bank_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='cheque_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='clrnce_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='crtd_date',
            field=models.DateTimeField(),
        ),
    ]
