# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-04-17 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_auto_20210417_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='bank_date_one',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='bank_date_two',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='bank_date',
            field=models.CharField(max_length=50),
        ),
    ]
