# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-04-26 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_auto_20210417_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='settled',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
