# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-04-27 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_banktransaction_settled'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransactionmaster',
            name='updated_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
