# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-05-01 05:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0008_banktransactionmaster_updated_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='is_amount_matched',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='banktransactionpaymentresponsemap',
            name='is_amount_matched',
            field=models.BooleanField(default=True),
        ),
    ]
