# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-05-01 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0009_auto_20210501_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='is_amount_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='banktransactionpaymentresponsemap',
            name='is_amount_matched',
            field=models.BooleanField(default=False),
        ),
    ]
