# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-06-19 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0010_auto_20210501_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='aggregrator',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='athrsd_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='bank_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='clrnce_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banktransaction',
            name='crtd_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
