# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-06-19 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0011_auto_20210619_0631'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='settlement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
