# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-06-25 09:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0131_employeeorderchangelog_session'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transaction', '0012_banktransaction_settlement_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransactionCarryForward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=50)),
                ('crtd_date', models.DateTimeField(blank=True, null=True)),
                ('is_carry_forward', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('bank_transaction_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.BankTransactionMaster')),
                ('bank_transaction_payment_response_map', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.BankTransactionPaymentResponseMap')),
                ('payment_response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PaymentRequestResponse')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
