# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-06-25 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0013_banktransactioncarryforward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransactioncarryforward',
            name='bank_transaction_master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transaction.BankTransactionMaster'),
        ),
    ]
