# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-02-09 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_messsage', '0003_auto_20210209_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='short_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
