# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-06 06:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesstypewiseproductdiscount',
            old_name='discount_price',
            new_name='discounted_price',
        ),
        migrations.RenameField(
            model_name='businesstypewiseproductdiscounttrace',
            old_name='discount_price',
            new_name='discounted_price',
        ),
        migrations.RenameField(
            model_name='businesswiseproductdiscount',
            old_name='discount_price',
            new_name='discounted_price',
        ),
        migrations.RenameField(
            model_name='businesswiseproductdiscounttrace',
            old_name='discount_price',
            new_name='discounted_price',
        ),
        migrations.RenameField(
            model_name='icustomerproductdiscount',
            old_name='discount_price',
            new_name='discounted_price',
        ),
        migrations.RenameField(
            model_name='icustomerproductdiscounttrace',
            old_name='discount_price',
            new_name='discounted_price',
        ),
    ]
