# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-06 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200106_0721'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCodeBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_code', models.CharField(max_length=10)),
                ('to_code', models.CharField(max_length=10)),
                ('last_code', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BusinessType')),
            ],
        ),
        migrations.DeleteModel(
            name='AgentCodeBank',
        ),
    ]
