# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-08 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='working_hours_from',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='working_hours_to',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
