# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-08 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200108_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=main.models.get_user_profile_image),
        ),
    ]
