# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-20 19:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_icustomer_aadhar_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstypewiseproductcommissiontrace',
            name='product_commission_ended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_commission_end_date_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
