# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-21 02:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200120_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstypewiseproductdiscounttrace',
            name='product_discount_ended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_type_wise_product_discount_end_date_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='businesswiseproductdiscounttrace',
            name='product_discount_ended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_type_product_discount_end_date_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='icustomertypewiseproductdiscounttrace',
            name='product_discount_ended_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='icustomer_product_product_discount_end_date_created_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
