# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-23 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20200121_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='routebusinessmap',
            name='ordinal',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='routebusinesstrace',
            name='ordinal',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routetrace',
            name='indent_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='routetrace',
            name='indent_prepare_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
