# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-23 09:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20200123_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='routetrace',
            name='indent_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.IndentStatus'),
            preserve_default=False,
        ),
    ]
