# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-28 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20200128_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='basic_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producttrace',
            name='basic_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fc_document',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=main.models.get_fc_document),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fc_expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_document',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=main.models.get_insurance_document),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
