# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-01-29 07:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_productavailabilitymap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='basic_price',
            new_name='base_price',
        ),
        migrations.RenameField(
            model_name='producttrace',
            old_name='basic_price',
            new_name='base_price',
        ),
    ]
