# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-03 07:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20200129_1038'),
    ]

    operations = [
        migrations.CreateModel(
            name='IcustomerProductMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('icustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ICustomer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
        ),
        migrations.RenameField(
            model_name='icustomertypewiseproductdiscounttrace',
            old_name='icostomer_type_wiser_product_discount',
            new_name='icustomer_type_wiser_product_discount',
        ),
        migrations.AddField(
            model_name='businesstype',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icustomertype',
            name='milk_limit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
