# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-05 07:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200203_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_ordinal',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
