# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-10 06:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0026_producttrayconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('value', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_config_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_modified_by', to=settings.AUTH_USER_MODEL)),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Union')),
            ],
        ),
        migrations.AlterField(
            model_name='producttrayconfig',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tray_config_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producttrayconfig',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tray_config_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
