# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-13 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200210_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporationZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
