# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-12 12:29
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20200210_0602'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=main.models.get_user_profile_image),
        ),
    ]
