# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-13 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_corporationzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='corporation_zone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.CorporationZone'),
            preserve_default=False,
        ),
    ]
