# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-15 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_ward_corporation_zone'),
        ('main', '0028_product_image'),
    ]

    operations = [
    ]
