# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-16 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20200215_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicletransport',
            name='contract_duration',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
