# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-17 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20200216_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicletransport',
            name='contract_duration',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='contract_ends_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='contract_strart_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
