# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-20 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20200217_0439'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryIcustomerData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('gender_id', models.PositiveIntegerField()),
                ('taluk_id', models.PositiveIntegerField()),
                ('district_id', models.PositiveIntegerField()),
                ('state_id', models.PositiveIntegerField()),
                ('pincode', models.PositiveIntegerField()),
                ('mobile', models.PositiveIntegerField()),
                ('alternate_mobile', models.PositiveIntegerField(blank=True, null=True)),
                ('street', models.TextField(blank=True, max_length=20, null=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
