# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-21 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_temporaryicustomerdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TemporaryIcustomerData',
        ),
        migrations.AlterField(
            model_name='icustomer',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Business'),
        ),
    ]
