# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-26 06:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20200221_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionChequeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=150)),
                ('branch_name', models.CharField(max_length=100)),
                ('ifsc_code', models.CharField(max_length=100)),
                ('micr_code', models.CharField(blank=True, max_length=100, null=True)),
                ('account_holder_name', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('date_of_issue', models.DateField()),
                ('cheque_number', models.PositiveIntegerField()),
                ('is_cleared', models.BooleanField(default=False)),
                ('cheque_cleared_date', models.DateField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='cheque_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.TransactionChequeDetails'),
        ),
    ]
