# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-28 10:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0038_counter_counteremployeetracemap_counteremployeetracesalegroupmap'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('mobile', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuantityVariationPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.DecimalField(decimal_places=3, max_digits=9)),
                ('max_quantity', models.DecimalField(decimal_places=3, max_digits=9)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=9)),
                ('is_active', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductQuantityVariationPriceTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.DecimalField(decimal_places=3, max_digits=9)),
                ('max_quantity', models.DecimalField(decimal_places=3, max_digits=9)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=9)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
                ('product_price_ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_quantity_variation_price_end_date_created_by', to=settings.AUTH_USER_MODEL)),
                ('product_price_started_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_quantity_variation_price_start_date_created_by', to=settings.AUTH_USER_MODEL)),
                ('product_quantity_variation_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProductQuantityVariationPrice')),
            ],
        ),
    ]
