# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-29 07:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0040_counter_collection_center'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverallIndentPerSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('overall_indent_document', models.FileField(blank=True, max_length=1000, null=True, upload_to=main.models.get_overall_indent_document)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overall_indent_created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactedVia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='routetrace',
            name='indent_document',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=main.models.get_route_trace_indent_document),
        ),
        migrations.AddField(
            model_name='transactionlog',
            name='data_entered_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_initiated_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transactionlog',
            name='transacted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_or_customer_user_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='overallindentpersession',
            name='route_trace',
            field=models.ManyToManyField(to='main.RouteTrace'),
        ),
        migrations.AddField(
            model_name='overallindentpersession',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Session'),
        ),
    ]
