# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-12 05:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0044_auto_20200309_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICustomerSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ICustomerSaleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Business')),
                ('icustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ICustomer')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icustomer_sale_group_modified_by', to=settings.AUTH_USER_MODEL)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icustomer_sale_group_created_by', to=settings.AUTH_USER_MODEL)),
                ('ordered_via', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.OrderedVia')),
                ('payment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PaymentStatus')),
                ('sale_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SaleStatus')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Session')),
            ],
        ),
        migrations.RemoveField(
            model_name='salegroup',
            name='icustomer',
        ),
        migrations.RemoveField(
            model_name='salegroup',
            name='sale_type',
        ),
        migrations.AlterField(
            model_name='sale',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sale_ordered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='icustomersale',
            name='icustomer_sale_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ICustomerSaleGroup'),
        ),
        migrations.AddField(
            model_name='icustomersale',
            name='modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icustomer_sale_modified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='icustomersale',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='icustomer_sale_ordered_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='icustomersale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
        migrations.AddField(
            model_name='counteremployeetracesalegroupmap',
            name='icustomer_sale_group',
            field=models.ManyToManyField(to='main.ICustomerSaleGroup'),
        ),
    ]
