# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-13 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20200312_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='icustomersale',
            name='cost_for_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icustomersalegroup',
            name='total_cost_for_month',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
