# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-18 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_auto_20200313_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='leak_packet_in_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
