# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-19 00:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_route_leak_packet_in_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessWiseLeakageAllowanceAsPacket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet_count', models.PositiveIntegerField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Business')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Session')),
            ],
        ),
        migrations.AlterField(
            model_name='route',
            name='leak_packet_in_percentage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
    ]
