# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-21 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20200319_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='routetracewisesalesummary',
            name='leak_packet_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routetracewisesalesummary',
            name='loose_packet_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='routetracewisesalesummary',
            name='tray_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
