# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-23 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_auto_20200321_0832'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndentCodeBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_for', models.CharField(max_length=100)),
                ('from_code', models.CharField(max_length=10)),
                ('to_code', models.CharField(max_length=10)),
                ('last_code', models.CharField(max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
