# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-04-02 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_indentcodebank'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteTempRouteMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='is_temp_route',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='routetemproutemap',
            name='main_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_route', to='main.Route'),
        ),
        migrations.AddField(
            model_name='routetemproutemap',
            name='temp_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_route_of_main_route', to='main.Route'),
        ),
    ]
