# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-04-02 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_auto_20200402_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='tray_capacity',
            field=models.IntegerField(default=450),
            preserve_default=False,
        ),
    ]
