# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-04-08 07:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_carrier_carrierfilemap_tender_tenderfilemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrierfilemap',
            name='document_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='tenderfilemap',
            name='document_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
