# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-04-08 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_auto_20200408_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrier',
            name='last_date_for_apply',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tender',
            name='ends_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
