# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-04-21 07:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20200408_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteGroupMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('full_name', models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='routegroupmap',
            name='eve_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eve_route', to='main.Route'),
        ),
        migrations.AddField(
            model_name='routegroupmap',
            name='eve_temp_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eve_temp_route', to='main.Route'),
        ),
        migrations.AddField(
            model_name='routegroupmap',
            name='mor_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mor_route', to='main.Route'),
        ),
        migrations.AddField(
            model_name='routegroupmap',
            name='mor_temp_route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mor_temp_route', to='main.Route'),
        ),
    ]
