# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-04-22 05:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20200421_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routegroupmap',
            name='eve_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eve_route', to='main.Route'),
        ),
        migrations.AlterField(
            model_name='routegroupmap',
            name='eve_temp_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eve_temp_route', to='main.Route'),
        ),
        migrations.AlterField(
            model_name='routegroupmap',
            name='mor_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mor_route', to='main.Route'),
        ),
        migrations.AlterField(
            model_name='routegroupmap',
            name='mor_temp_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mor_temp_route', to='main.Route'),
        ),
    ]
