# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-04-27 08:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_auto_20200422_0542'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesstype',
            name='display_ordinal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
