# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-19 07:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0058_businesstype_display_ordinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='routegroupmap',
            name='union',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Union'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='icustomersalegroup',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='salegroup',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
