# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-22 13:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_businesstypewiseproductminimumquantityinlitre'),
    ]

    operations = [
        migrations.AddField(
            model_name='icustomersalegroup',
            name='route',
            field=models.ForeignKey(default=85, on_delete=django.db.models.deletion.CASCADE, to='main.Route'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icustomersalegroup',
            name='zone',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='main.Zone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salegroup',
            name='route',
            field=models.ForeignKey(default=85, on_delete=django.db.models.deletion.CASCADE, to='main.Route'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salegroup',
            name='zone',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='main.Zone'),
            preserve_default=False,
        ),
    ]
