# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-29 13:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0061_auto_20200522_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAgentCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_codes', models.CharField(max_length=60)),
                ('tm_cash_milk_sale', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tm_cash_milk_comm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tm_card_milk_sale', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tm_card_milk_comm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sm_cash_milk_sale', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sm_cash_milk_comm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sm_card_milk_sale', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sm_card_milk_comm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fcm_cash_milk_sale', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fcm_cash_milk_comm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fcm_card_milk_sale', models.DecimalField(decimal_places=2, max_digits=9)),
                ('fcm_card_milk_comm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('can_milk_sale', models.DecimalField(decimal_places=2, max_digits=9)),
                ('can_milk_comm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_cash_milk_sale', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_cash_milk_comm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_card_milk_sale', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_card_milk_comm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_milk_sale', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total_milk_comm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('gross_comm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tds_deduction', models.DecimalField(decimal_places=2, max_digits=9)),
                ('insurance_deduction', models.DecimalField(decimal_places=2, max_digits=9)),
                ('slip_charge', models.DecimalField(decimal_places=2, max_digits=9)),
                ('gross_deduction', models.DecimalField(decimal_places=2, max_digits=9)),
                ('net_comm', models.DecimalField(decimal_places=2, max_digits=9)),
                ('comm_calculated_at', models.DateTimeField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Agent')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Business')),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BusinessType')),
                ('comm_calculated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyAgentCommissionRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField()),
                ('month', models.PositiveSmallIntegerField()),
                ('split', models.PositiveIntegerField()),
                ('run_from', models.DateTimeField()),
                ('run_to', models.DateTimeField()),
                ('card_milk_comm_percentage', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cash_milk_comm_percentage', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tds_deduction_percentage', models.DecimalField(decimal_places=2, max_digits=9)),
                ('insurance_deduction_percentage', models.DecimalField(decimal_places=2, max_digits=9)),
                ('slip_charge', models.DecimalField(decimal_places=2, max_digits=9)),
                ('is_comm_calculation_approved', models.BooleanField(default=False)),
                ('comm_calculation_approved_at', models.DateTimeField(blank=True, null=True)),
                ('comm_calculated_at', models.DateTimeField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('comm_calculated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comm_calculation_approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comm_calculation_approved_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyAgentCommissionRunDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(max_length=1000, upload_to=main.models.get_monthly_agent_commission_run_document)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MonthlyAgentCommissionRun')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyAgentCommissionTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_transaction_id', models.CharField(max_length=60)),
                ('bank_transaction_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('bank_transaction_date', models.DateTimeField()),
                ('destination_bank_account_number', models.CharField(max_length=60)),
                ('comm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.MonthlyAgentCommission')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProductSubGroupMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='productproductsubgroupmap',
            name='product_sub_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProductSubGroup'),
        ),
        migrations.AddField(
            model_name='monthlyagentcommission',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MonthlyAgentCommissionRun'),
        ),
    ]
