# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-05-29 14:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0062_auto_20200529_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monthlyagentcommission',
            old_name='total_milk_comm',
            new_name='gross_sale',
        ),
        migrations.RemoveField(
            model_name='monthlyagentcommission',
            name='total_milk_sale',
        ),
    ]
