# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-06-11 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0063_auto_20200529_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MenuHeaderPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('menu_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MenuHeader')),
            ],
        ),
        migrations.CreateModel(
            name='MenuHeaderPagePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('employee_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.EmployeeRole')),
                ('menu_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MenuHeaderPage')),
            ],
        ),
        migrations.CreateModel(
            name='MenuHeaderPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('employee_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.EmployeeRole')),
                ('menu_header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MenuHeader')),
            ],
        ),
    ]
