# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-06-11 13:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0064_menuheader_menuheaderpage_menuheaderpagepermission_menuheaderpermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuheaderpagepermission',
            old_name='menu_header',
            new_name='menu_header_page',
        ),
    ]
