# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-06-12 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0065_auto_20200611_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuheader',
            name='ordinal',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menuheaderpage',
            name='ordinal',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
