# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-06-17 06:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0066_auto_20200612_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=20)),
                ('encrypted_string', models.TextField()),
                ('decrypted_string', models.TextField()),
                ('ver', models.CharField(max_length=3)),
                ('cid', models.CharField(max_length=4)),
                ('typ', models.CharField(max_length=4)),
                ('crn', models.CharField(max_length=20)),
                ('brn', models.CharField(max_length=10)),
                ('cks', models.CharField(max_length=4096)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EnquiryRequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=20, unique=True)),
                ('encrypted_string', models.TextField()),
                ('decrypted_string', models.TextField()),
                ('brn', models.CharField(max_length=10)),
                ('trn', models.CharField(max_length=40, unique=True)),
                ('tet', models.DateTimeField()),
                ('pmd', models.CharField(max_length=5)),
                ('ver', models.CharField(max_length=3)),
                ('cid', models.CharField(max_length=4)),
                ('typ', models.CharField(max_length=4)),
                ('crn', models.CharField(max_length=20, unique=True)),
                ('cny', models.CharField(max_length=3)),
                ('amt', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cks', models.CharField(max_length=4096)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('enquiry_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.EnquiryRequest')),
            ],
        ),
        migrations.CreateModel(
            name='ICustomerSaleGroupPaymentRequestMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=20, unique=True)),
                ('encrypted_string', models.TextField()),
                ('decrypted_string', models.TextField()),
                ('ver', models.CharField(max_length=3)),
                ('cid', models.CharField(max_length=4)),
                ('typ', models.CharField(max_length=4)),
                ('crn', models.CharField(max_length=20, unique=True)),
                ('cny', models.CharField(max_length=3)),
                ('amt', models.DecimalField(decimal_places=2, max_digits=9)),
                ('rtu', models.CharField(max_length=1024)),
                ('ppi', models.CharField(max_length=1024)),
                ('re1', models.CharField(max_length=3, null=True)),
                ('re2', models.CharField(max_length=3, null=True)),
                ('re3', models.CharField(max_length=3, null=True)),
                ('re4', models.CharField(max_length=3, null=True)),
                ('re5', models.CharField(max_length=3, null=True)),
                ('cks', models.CharField(max_length=4096)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequestPPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=25)),
                ('value', models.CharField(max_length=256)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PaymentRequest')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequestResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rid', models.CharField(max_length=20, unique=True)),
                ('is_enquired', models.BooleanField(default=False)),
                ('encrypted_string', models.TextField()),
                ('decrypted_string', models.TextField()),
                ('brn', models.CharField(max_length=10)),
                ('trn', models.CharField(max_length=40, unique=True)),
                ('tet', models.DateTimeField()),
                ('pmd', models.CharField(max_length=5)),
                ('ver', models.CharField(max_length=3)),
                ('cid', models.CharField(max_length=4)),
                ('typ', models.CharField(max_length=4)),
                ('crn', models.CharField(max_length=20, unique=True)),
                ('cny', models.CharField(max_length=3)),
                ('amt', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cks', models.CharField(max_length=4096)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('payment_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.PaymentRequest')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('solution', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRequestUserMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('payment_intitated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PaymentRequest')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransactionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SaleGroupPaymentRequestMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PaymentRequest')),
                ('sale_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SaleGroup')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='reference_order_expiry_time',
            field=models.TimeField(default='17:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequestresponse',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PaymentTransactionStatus'),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PaymentRequestStatus'),
        ),
        migrations.AddField(
            model_name='icustomersalegrouppaymentrequestmap',
            name='payment_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PaymentRequest'),
        ),
        migrations.AddField(
            model_name='icustomersalegrouppaymentrequestmap',
            name='sale_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ICustomerSaleGroup'),
        ),
        migrations.AddField(
            model_name='enquiryrequestresponse',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PaymentTransactionStatus'),
        ),
        migrations.AddField(
            model_name='enquiryrequest',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PaymentRequestStatus'),
        ),
    ]
