# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-06-17 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20200617_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequestIdBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_count', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
