# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-06-18 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0069_auto_20200618_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='counteremployeetracemap',
            name='is_included_in_cash_collection_report',
            field=models.BooleanField(default=True),
        ),
    ]
