# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-06-18 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_counteremployeetracemap_is_included_in_cash_collection_report'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counteremployeetracemap',
            name='is_included_in_cash_collection_report',
        ),
        migrations.AddField(
            model_name='counter',
            name='is_included_in_cash_collection_report',
            field=models.BooleanField(default=True),
        ),
    ]
