# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-07-24 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_icustomercardserialnumberidbank_icustomermilkcarknumberidbank_icustomermonthlyordertransaction_icust'),
    ]

    operations = [
        migrations.AddField(
            model_name='icustomermonthlyordertransaction',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='icustomermonthlyordertransaction',
            name='milk_card_number',
            field=models.CharField(max_length=50),
        ),
    ]
