# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-07-25 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_auto_20200724_1100'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethodCv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='paymentrequestresponse',
            name='rmk',
            field=models.CharField(default=' ', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentrequestresponse',
            name='stc',
            field=models.CharField(default=' ', max_length=5),
            preserve_default=False,
        ),
    ]
