# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-07-25 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0075_auto_20200725_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequestresponse',
            name='rmk',
            field=models.CharField(max_length=25),
        ),
    ]
