# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-07-30 12:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0080_auto_20200730_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='icustomersalegrouppaymentrequestmap',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='icustomersalegrouppaymentrequestmap',
            name='temp_sale_group',
            field=models.ManyToManyField(to='main.TempICustomerSaleGroup'),
        ),
        migrations.RemoveField(
            model_name='icustomersalegrouppaymentrequestmap',
            name='sale_group',
        ),
        migrations.AddField(
            model_name='icustomersalegrouppaymentrequestmap',
            name='sale_group',
            field=models.ManyToManyField(to='main.ICustomerSaleGroup'),
        ),
    ]
