# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-02 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0081_auto_20200730_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='icustomer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
