# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-03 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0084_agent_is_mobile_number_verified_by_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAgentCommissionRunColumnCv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column_name', models.CharField(max_length=50)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MonthlyAgentCommissionRun')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyAgentCommissionSubColumn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=9)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('agent_commission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MonthlyAgentCommission')),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.MonthlyAgentCommissionRunColumnCv')),
            ],
        ),
    ]
