# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-04 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0086_auto_20200804_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='is_wallet_selected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='wallet_balance_after_this_transaction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
