# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-04 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0087_auto_20200804_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='is_amount_returened_to_wallet',
            field=models.BooleanField(default=False),
        ),
    ]
