# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-07 10:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0089_icustomer_is_aadhar_number_verified_by_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiryrequest',
            name='brn',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enquiryrequestresponse',
            name='crn',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiryrequestresponse',
            name='rid',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiryrequestresponse',
            name='trn',
            field=models.CharField(max_length=40),
        ),
    ]
