# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-07 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0090_auto_20200807_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryrequest',
            name='enquiry_make_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
