# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-07 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0091_enquiryrequest_enquiry_make_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiryrequestresponse',
            name='rmk',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enquiryrequestresponse',
            name='stc',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
    ]
