# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-08 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0092_auto_20200807_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.TextField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=13)),
                ('alternate_mobile', models.CharField(blank=True, max_length=13, null=True)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, max_length=1000, null=True, upload_to=main.models.get_user_profile_image)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.District')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Gender')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.State')),
                ('taluk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Taluk')),
                ('union', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Union')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='email',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='agent',
            name='first_name',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agent',
            name='agent_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.AgentProfile'),
        ),
    ]
