# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-08 08:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0093_auto_20200808_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRouteChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField()),
                ('description', models.TextField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ICustomerBusinessLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('icustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ICustomer')),
            ],
        ),
        migrations.CreateModel(
            name='RouteTimeChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=50)),
                ('old_time', models.TimeField()),
                ('new_time', models.TimeField()),
                ('changed_at', models.DateTimeField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Session')),
            ],
        ),
        migrations.CreateModel(
            name='SaleGroupDeleteLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ordered_date_time', models.DateTimeField()),
                ('delete_date_time', models.DateTimeField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='agent',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile_modified_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='business_created_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='modified_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='business_modified_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agent',
            name='communication_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='relation_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='agent',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.RelationType'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='image',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to=main.models.get_agent_user_profile_image),
        ),
        migrations.AddField(
            model_name='salegroupdeletelog',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Business'),
        ),
        migrations.AddField(
            model_name='salegroupdeletelog',
            name='deleted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_deleted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salegroupdeletelog',
            name='ordered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_placed_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salegroupdeletelog',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Session'),
        ),
        migrations.AddField(
            model_name='icustomerbusinesslog',
            name='new_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_business', to='main.Business'),
        ),
        migrations.AddField(
            model_name='icustomerbusinesslog',
            name='old_business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_business', to='main.Business'),
        ),
        migrations.AddField(
            model_name='businessroutechangelog',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Business'),
        ),
        migrations.AddField(
            model_name='businessroutechangelog',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='businessroutechangelog',
            name='new_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='new_oute', to='main.Route'),
        ),
        migrations.AddField(
            model_name='businessroutechangelog',
            name='old_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_route', to='main.Route'),
        ),
    ]
