# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-08 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0094_auto_20200808_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='is_mobile_number_verified_by_agent',
        ),
        migrations.AddField(
            model_name='business',
            name='is_mobile_number_verified_by_agent',
            field=models.BooleanField(default=False),
        ),
    ]
