# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-11 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0096_auto_20200808_1228'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='salegroup',
            unique_together=set([('business', 'session', 'date')]),
        ),
    ]
