# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-20 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0097_auto_20200811_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAutoEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.DateTimeField()),
                ('run_interval_start', models.DateTimeField()),
                ('run_interval_end', models.DateTimeField()),
                ('run_type', models.CharField(max_length=25)),
                ('candidate_count', models.PositiveIntegerField()),
                ('success_count', models.PositiveIntegerField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentAutoEnquiryProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_sent_to_wallet', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_order_placed', models.BooleanField(default=False)),
                ('morning_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('evening_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('evening_sale_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evening_sale_group', to='main.SaleGroup')),
                ('morning_sale_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='morning_sale_group', to='main.SaleGroup')),
                ('payment_auto_enquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PaymentAutoEnquiry')),
                ('payment_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.PaymentRequest')),
            ],
        ),
    ]
