# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-20 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0098_paymentautoenquiry_paymentautoenquiryproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrequest',
            name='enquiry_response_status_latest',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.PaymentTransactionStatus'),
            preserve_default=False,
        ),
    ]
