# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-20 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0099_paymentrequest_enquiry_response_status_latest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrequest',
            name='enquiry_response_status_latest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.PaymentTransactionStatus'),
        ),
    ]
