# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-08-25 07:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0101_paymentrequest_ordered_via'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTypeWiseOverallLitreLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('litre_limit', models.DecimalField(decimal_places=2, max_digits=9)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BusinessType')),
            ],
        ),
    ]
