# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-09-28 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0106_businesswisebillnumber_instititionbillnumberidbank'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesswisebillnumber',
            name='product_group_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.ProductGroup'),
            preserve_default=False,
        ),
    ]
