# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-09-28 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0107_businesswisebillnumber_product_group_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='society_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
