# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-29 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0109_auto_20201008_0544'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleGroupOrderType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleGroupTransactionTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('counter_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transacted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('wallet_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bank_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('wallet_transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_wallet_used', models.BooleanField(default=False)),
                ('order_sale_group_json', models.TextField(blank=True, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Counter')),
                ('sale_group_order_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SaleGroupOrderType')),
            ],
        ),
        migrations.CreateModel(
            name='SuperSaleGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Business')),
                ('eve_sale_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eve_sale_group', to='main.SaleGroup')),
                ('mor_sale_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mor_sale_group', to='main.SaleGroup')),
            ],
        ),
        migrations.AddField(
            model_name='salegrouptransactiontrace',
            name='super_sale_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SuperSaleGroup'),
        ),
    ]
