# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-30 05:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0110_auto_20201029_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salegrouptransactiontrace',
            name='bank_transaction_id',
        ),
        migrations.RemoveField(
            model_name='salegrouptransactiontrace',
            name='wallet_transaction_id',
        ),
        migrations.AddField(
            model_name='salegrouptransactiontrace',
            name='bank_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bank_transaction_log', to='main.TransactionLog'),
        ),
        migrations.AddField(
            model_name='salegrouptransactiontrace',
            name='counter_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='counter_transaction_log', to='main.TransactionLog'),
        ),
        migrations.AddField(
            model_name='salegrouptransactiontrace',
            name='wallet_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_transaction_log', to='main.TransactionLog'),
        ),
    ]
