# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-10-30 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0111_auto_20201030_0501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supersalegroup',
            name='eve_sale_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eve_sale_group', to='main.SaleGroup'),
        ),
        migrations.AlterField(
            model_name='supersalegroup',
            name='mor_sale_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mor_sale_group', to='main.SaleGroup'),
        ),
    ]
