# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-11-24 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0112_auto_20201030_0740'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnionForIcustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('short_name', models.CharField(blank=True, max_length=40, null=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='icustomer',
            name='union_for_icustomer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.UnionForIcustomer'),
        ),
    ]
