# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-12-23 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0116_customerorderdeletelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorderdeletelog',
            name='deleted_value_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
