# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-01-13 07:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0117_customerorderdeletelog_deleted_value_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeMonthlyOrderLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_for', models.CharField(max_length=50)),
                ('time_statrted', models.DateTimeField()),
                ('time_ended', models.DateTimeField()),
                ('order_for_date', models.DateTimeField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('ordered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
