# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-01-13 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0119_auto_20210113_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemonthlyorderlog',
            name='time_ended',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
