# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-03-31 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0120_auto_20210113_0727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesstype',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
