# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-04-22 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0123_auto_20210416_0628'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
            ],
        ),
    ]
