# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-04-29 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0125_routegroupmap_route_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='routecity',
            name='display_ordinal',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
