# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-05-16 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0126_routecity_display_ordinal'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_working_now',
            field=models.BooleanField(default=True),
        ),
    ]
