# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-05-22 13:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0127_business_is_working_now'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeChangeOrderChangeMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeOrderChangeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_delivery', models.DateField()),
                ('total_days', models.PositiveSmallIntegerField()),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('modified_at', models.DateTimeField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('employee_order_change_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.EmployeeChangeOrderChangeMode')),
                ('icustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ICustomer')),
                ('icustomer_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.ICustomerSale')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
