# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-07-05 11:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0131_employeeorderchangelog_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='ICustomerWalletAmoutForOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month', models.PositiveIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('icustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ICustomer')),
                ('icustomer_sale_group', models.ManyToManyField(to='main.ICustomerSaleGroup')),
            ],
        ),
    ]
