# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-07-28 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0132_icustomerwalletamoutfororder'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessTypeWiseFutureOrderConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_future_order_accept', models.BooleanField(default=False)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('business_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.BusinessType')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDateModifyToggle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_order_data_changeable', models.BooleanField(default=False)),
            ],
        ),
    ]
