# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-10-01 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0137_auto_20210823_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyagentcommissionrun',
            name='comm_run_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyagentcommissionrun',
            name='comm_run_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='monthlyagentcommissionrun',
            name='is_comm_run_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='monthlyagentcommissionrun',
            name='comm_calculated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
