# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2021-11-23 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0138_auto_20211001_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='salegroup',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.BusinessType'),
        ),
        migrations.AddField(
            model_name='tempsalegroup',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.BusinessType'),
        ),
        migrations.AddField(
            model_name='tempsalegroupforedit',
            name='business_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.BusinessType'),
        ),
    ]
