# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-01-22 11:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0140_auto_20211223_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='gst_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
