# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-04-04 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0141_agentprofile_gst_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='account_code',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True),
        ),
    ]
