# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-04-17 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0142_business_account_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductShotnameAndQuantityTrace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('short_name', models.CharField(max_length=50)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=9)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ProductUnit')),
            ],
        ),
    ]
