# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-07-08 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0145_auto_20220701_0117'),
    ]

    operations = [
        migrations.CreateModel(
            name='BsnlSmsTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_name', models.CharField(max_length=30)),
                ('template_id', models.CharField(max_length=30)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
