# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2022-12-08 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0147_auto_20220802_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyagentcommission',
            name='tea_card_milk_comm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='monthlyagentcommission',
            name='tea_card_milk_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='monthlyagentcommission',
            name='tea_cash_milk_comm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='monthlyagentcommission',
            name='tea_cash_milk_sale',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
