name: Deploy to Amazon ECS (QA)
on:
 push:
   branches:
     - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: qa

    steps:
    - name: Checkout
      uses: actions/checkout@v3
     
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 068593391532.dkr.ecr.ap-south-1.amazonaws.com
      run: |
        docker build -t aavin-dev .
        docker tag aavin-dev:latest 068593391532.dkr.ecr.ap-south-1.amazonaws.com/aavin-dev:latest
        docker push 068593391532.dkr.ecr.ap-south-1.amazonaws.com/aavin-dev:latest
